### ISSUE TITLE
Relative paths

### ISSUE THREAD

**Issue by HugoHeneault** [pocketjoso/penthouse#95] opened 2015-12-02 10:52 UTC
Hi there. 

Thanks for your awesome tool!

I have a question regarding [this](https://github.com/pocketjoso/penthouse#background-images-or-fonts-missing) :
> ### Background images or Fonts missing
> Change any relative paths (f.e. background-image: url("../images/x.gif");) to absolute (starting with a /): background-image: url("/images/x.gif");, and then try again.

What if I can't use absolute paths? :cry: 
Why penthouse is not able to detect it?

**Comment by pocketjoso** [comment] 2015-12-02 20:23
The problem is that your css is very likely to be served from a different directory when it is inlined as critical css, so any relative paths in the css would need to be rebased. As`Penthouse` just accepts css as input it has no knowledge of what directory it will be hosted from, so it can't know how to rebase relative paths.

Making the paths absolute is probably the easiest solution for you, otherwise you can [rebase them yourself](https://github.com/addyosmani/critical/blob/master/lib/inline-styles.js#L61-L95), or perhaps just use [critical](https://github.com/addyosmani/critical) which is basically `penthouse` with extra functionality, such as rebasing relative paths.

I will not add in path rebasing to `Penthouse`, however I have written my own module for doing so - I will look into open sourcing it soon.

Closing as there's nothing for `Penthouse` to change here, but feel free to continue posting comments.

**Closed by pocketjoso** 2015-12-02 20:23 UTC
