### ISSUE TITLE
TypeError: Cannot read property 'clear' of undefined

### ISSUE THREAD

**Issue by lucasrla** [pocketjoso/penthouse#342] opened 2022-03-16 01:05 UTC
Hey, thanks for this project! 

I ran into what seems like a bug while using [critical](https://github.com/addyosmani/critical)@4.0.1 with [gulp](https://github.com/gulpjs/gulp)@4.0.2. The error message reads:

```log
Error in plugin "critical"
Message:
    Evaluation failed: TypeError: Cannot read property 'clear' of undefined
    at isElementAboveFold (__puppeteer_evaluation_script__:20:44)
    at isSelectorCritical (__puppeteer_evaluation_script__:67:11)
    at Array.filter (<anonymous>)
    at filterSelectors (__puppeteer_evaluation_script__:77:27)
    at pruneNonCriticalSelectors (__puppeteer_evaluation_script__:82:10)
Details:
    domainEmitter: [object Object]
    domainThrown: false
```

As far as I could find out (h/t [Tom-Bonnike](https://github.com/Tom-Bonnike/netlify-plugin-inline-critical-css/issues/6#issuecomment-635290330)), the cause of this error is [KaTeX](https://katex.org)'s selector `.katex *` (source: [unminified katex.css](https://cdn.jsdelivr.net/npm/katex@0.15.3/dist/katex.css)) being applied to "uncommon" elements (`<math>`, `<semantics>`) that don't seem to have the `style` attribute defined.

The likely offending lines are [pruneNonCriticalSelectors.js#L23:L24](https://github.com/pocketjoso/penthouse/blob/78c7cddba3c8d30785c1e654de2981c29f2c941c/src/browser-sandbox/pruneNonCriticalSelectors.js#L23:L24):

```js
var originalClearStyle = element.style.clear || ''
element.style.clear = 'none'
```

I put together a quick fix. It checks if each element has a `style` attribute before [calling `isElementAboveFold`](https://github.com/pocketjoso/penthouse/blob/78c7cddba3c8d30785c1e654de2981c29f2c941c/src/browser-sandbox/pruneNonCriticalSelectors.js#L70). Here's the [commit at my fork](https://github.com/lucasrla/penthouse/commit/b503d5ca44c6bbaaedc2e230ddf37d6b21e124fa) (branch [fix-element-style-undefined](https://github.com/lucasrla/penthouse/tree/fix-element-style-undefined)). Happy to submit it as a PR if this is good enough for you.

***

Steps to reproduce:

```sh
mkdir katex-test && cd katex-test
npm install gulp critical
node_modules/.bin/gulp critical_css
```

`gulpfile.js`:

```js
const gulp = require('gulp');
const critical = require('critical');

const criticalCss = () =>
  gulp.src('katex-test.html')
    .pipe(critical.stream({
      inline: false,
      extract: false,
      dimensions: [
        {
          width: 544,
          height: 999,
        },
      ],
    }))
    .pipe(gulp.dest('./'));

exports.critical_css = gulp.parallel(criticalCss);
```

`katex-test.html`:

```html
<html>
  <head>
    <title>KaTeX Test</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.3/dist/katex.min.css" crossorigin="anonymous">
  </head>
  <body>
    <p style="margin-top:2000px">
      <span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mtext>KaTeX</mtext></mrow><annotation encoding="application/x-tex">{\KaTeX}</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.8988em;vertical-align:-0.2155em;"></span><span class="mord"><span class="mord text"><span class="mord textrm">K</span><span class="mspace" style="margin-right:-0.17em;"></span><span class="vlist-t"><span class="vlist-r"><span class="vlist" style="height:0.6833em;"><span style="top:-2.905em;"><span class="pstrut" style="height:2.7em;"></span><span class="mord"><span class="mord textrm mtight sizing reset-size6 size3">A</span></span></span></span></span></span><span class="mspace" style="margin-right:-0.15em;"></span><span class="mord text"><span class="mord textrm">T</span><span class="mspace" style="margin-right:-0.1667em;"></span><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:0.4678em;"><span style="top:-2.7845em;"><span class="pstrut" style="height:3em;"></span><span class="mord"><span class="mord textrm">E</span></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height:0.2155em;"><span></span></span></span></span><span class="mspace" style="margin-right:-0.125em;"></span><span class="mord textrm">X</span></span></span></span></span></span></span>
    </p>
  </body>
</html>
```

PS: Note that this error does not happen if `<p>`'s margin-top is not a huge value. I am not sufficiently familiar with penthouse codebase to know why. But it could be that this kind of error only happens if the element that is missing the `style` attribute is not "obviously" above the fold?

**Comment by pocketjoso** [comment] 2022-03-26 13:21
Hi!

Thanks for the excellent bug report, including the clear reproducible test case.

I think you're right, the problem is indeed that unlike regular HTMLElements, math elements like `semantics` do not have a `style` attribute. So we need to add a guard for that. I looked at your branch with the fix - I'm just not confident that all elements without a style attribute can be considered non critical. To be safer I would suggest making a change on these lines instead:
https://github.com/pocketjoso/penthouse/blob/78c7cddba3c8d30785c1e654de2981c29f2c941c/src/browser-sandbox/pruneNonCriticalSelectors.js#L23-L30

To only conditionally set and reset the `style.clear` value if the `style` attribute exists, while leaving the [aboveFold computation](https://github.com/pocketjoso/penthouse/blob/78c7cddba3c8d30785c1e654de2981c29f2c941c/src/browser-sandbox/pruneNonCriticalSelectors.js#L25-L27) as it is today - so it's used also for these elements.

If you update your branch and push a PR for this we can get it merged in. :)

----

I didn't try out your case yet, to answer why this only happens for you with the margin-top on the p element, I will look at that next. The fix for the style attribute should be merged in either case, but I'm curious exactly what's going to make it only happen with the margin for you.

**Comment by lucasrla** [comment] 2022-03-27 17:57
Hey, thanks for the input. I have just submitted a PR (#343) that follows your suggestion.

Re the `margin-top` thing, looking forward to learning what's going on there!

**Closed** 2022-03-28 16:59 UTC
Labels: bug
